import {SportStores} from '../supersports/supersport';
import { Product } from '../products/products';

export const STOREDATA:SportStores[] = [{
		id: 1,
		address: 'Vinegade 109',
		city: '5000 Odense',
		phone: 99886622
	}, {
		id: 2,
		address: 'Vestergade 910',
		city: '9000 Aalborg',
		phone: 96819191
	}];

export const PRODUCTITEMS:Product[] = [{
		id: 1,
		name: 'GEL-FUJITRABUCO 5 G-TX',
		imgthumb: 'asics_thumb',
		img1: 'asics1',
		img2: 'asics2',
		img3: 'asics3',
		category: 'Running shoe',
		brandlogo: 'assets/img/brand_logo.jpg',
		shortdescription: 'God og robust terrænløbesko med GORE-TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod.',
		longdescription: 'The new GEL-FujiTrabuco™ 4 Neutral continues to offer off-road runners the balanced blend of cushioning, responsiveness, and versatile traction. The reverse lug pattern of the Trail-Specific Outsole and Rock Protection Plate provide excellent protection on a variety of uneven terrains. The new upper design has been updated for a more comfortable fit and durable performance, hugging the foot with modified MONO-SOCK® construction and Heel Clutching System™. Weight: 11.7 oz. Heel Height: 20mm. Forefoot Height: 10mm. Pronation is how a runners foot rolls medially between footfall and toeoff. Underpronation is when the foot rolls outwards, overpronation is when it rolls inwards, and a neutral pattern is when little rolling occurs. Matching a shoes properties with the runners running style will increase comfort, running efficiency, and contribute to decreasing the risk of injury.',
		fullprice: 88.99,
		discount: 0.15,
		stars: 5,
		size: ['12', '14'],
		isfavorite: true,
		popularproduct: false

	}, {
		id: 2,
		name: 'GEL-FUJITRABUCO 5 G-TX',
		imgthumb: 'asics_thumb',
		img1: 'asics1',
		img2: 'asics2',
		img3: 'asics3',
		category: 'Running shoe',
		brandlogo: 'assets/img/brand_logo.jpg',
		shortdescription: 'God og robust terrænløbesko med GORE-TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod.',
		longdescription: 'The new GEL-FujiTrabuco™ 4 Neutral continues to offer off-road runners the balanced blend of cushioning, responsiveness, and versatile traction. The reverse lug pattern of the Trail-Specific Outsole and Rock Protection Plate provide excellent protection on a variety of uneven terrains. The new upper design has been updated for a more comfortable fit and durable performance, hugging the foot with modified MONO-SOCK® construction and Heel Clutching System™. Weight: 11.7 oz. Heel Height: 20mm. Forefoot Height: 10mm. Pronation is how a runners foot rolls medially between footfall and toeoff. Underpronation is when the foot rolls outwards, overpronation is when it rolls inwards, and a neutral pattern is when little rolling occurs. Matching a shoes properties with the runners running style will increase comfort, running efficiency, and contribute to decreasing the risk of injury.',
		fullprice: 1115.22,
		discount: 0.15,
		stars: 2,
		size: ['EU 42 Black', 'EU 40 Black', 'EU 38 Black'],
		isfavorite: false,
		popularproduct: true
	}, {
		id: 3,
		name: 'Nike Free Black',
		imgthumb: 'nike_thumb',
		img1: 'nike1',
		img2: 'nike2',
		img3: 'nike3',
		category: 'Running shoe',
		brandlogo: 'assets/img/nike-logo.png',
		shortdescription: 'Nike Free RN er den klassiske Nike Free 5.0 i nye klæder. Opbygningen af skoen lader ingen tvivl om at vi har med en Nike Free at gøre.',
		longdescription: 'Nike Free RN er den klassiske Nike Free 5.0 i nye klæder. Opbygningen af skoen lader ingen tvivl om at vi har med en Nike Free at gøre. Overdelen er lavet i en Flymesh med zone inddelt ventilation, og Flywire i snøringen for at give et optimalt hold og støtte. Største nyhed er den nye mellemsålsopbygning. En auxetisk geometrisk opbygget mellemsål, giver efter og trækker sig sammen alt efter belastning. Det giver et mere naturligt bevægelsesmønster. Enginered mesh overdel med ventilationszoner. Flywire kabler for en tæt snøring og fast hold.',
		fullprice: 799.50,
		discount: 0.10,
		stars: 5,
		size: ['EU 36 Black', 'EU 38 Black', 'EU 39 Black'],
		isfavorite: false,
		popularproduct: true
	}, {
		id: 4,
		name: 'GEL-FUJITRABUCO 5 G-TX',
		imgthumb: 'asics_thumb',
		img1: 'asics1',
		img2: 'asics2',
		img3: 'asics3',
		category: 'Running shoe',
		brandlogo: 'assets/img/brand_logo.jpg',
		shortdescription: 'God og robust terrænløbesko med GORE-TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod.',
		longdescription: 'The new GEL-FujiTrabuco™ 4 Neutral continues to offer off-road runners the balanced blend of cushioning, responsiveness, and versatile traction. The reverse lug pattern of the Trail-Specific Outsole and Rock Protection Plate provide excellent protection on a variety of uneven terrains. The new upper design has been updated for a more comfortable fit and durable performance, hugging the foot with modified MONO-SOCK® construction and Heel Clutching System™. Weight: 11.7 oz. Heel Height: 20mm. Forefoot Height: 10mm. Pronation is how a runners foot rolls medially between footfall and toeoff. Underpronation is when the foot rolls outwards, overpronation is when it rolls inwards, and a neutral pattern is when little rolling occurs. Matching a shoes properties with the runners running style will increase comfort, running efficiency, and contribute to decreasing the risk of injury.',
		fullprice: 88.99,
		discount: 0.15,
		stars: 3,
		size: ['12', '14', '16'],
		isfavorite: false,
		popularproduct: true
	}, {
		id: 5,
		name: 'Nike Free Black',
		imgthumb: 'nike_thumb',
		img1: 'nike1',
		img2: 'nike2',
		img3: 'nike3',
		category: 'Running shoe',
		brandlogo: 'assets/img/nike-logo.png',
		shortdescription: 'Nike Free RN er den klassiske Nike Free 5.0 i nye klæder. Opbygningen af skoen lader ingen tvivl om at vi har med en Nike Free at gøre.',
		longdescription: 'The new GEL-FujiTrabuco™ 4 Neutral continues to offer off-road runners the balanced blend of cushioning, responsiveness, and versatile traction. The reverse lug pattern of the Trail-Specific Outsole and Rock Protection Plate provide excellent protection on a variety of uneven terrains. The new upper design has been updated for a more comfortable fit and durable performance, hugging the foot with modified MONO-SOCK® construction and Heel Clutching System™. Weight: 11.7 oz. Heel Height: 20mm. Forefoot Height: 10mm. Pronation is how a runners foot rolls medially between footfall and toeoff. Underpronation is when the foot rolls outwards, overpronation is when it rolls inwards, and a neutral pattern is when little rolling occurs. Matching a shoes properties with the runners running style will increase comfort, running efficiency, and contribute to decreasing the risk of injury.',
		fullprice: 799.50,
		discount: 0.10,
		stars: 5,
		size: ['EU 36 Black', 'EU 38 Black', 'EU 39 Black'],
		isfavorite: false,
		popularproduct: true
	}, {
		id: 6,
		name: 'GEL-FUJITRABUCO 5 G-TX',
		imgthumb: 'asics_thumb',
		img1: 'asics1',
		img2: 'asics2',
		img3: 'asics3',
		category: 'Running shoe',
		brandlogo: 'assets/img/brand_logo.jpg',
		shortdescription: 'God og robust terrænløbesko med GORE-TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod.',
		longdescription: 'The new GEL-FujiTrabuco™ 4 Neutral continues to offer off-road runners the balanced blend of cushioning, responsiveness, and versatile traction. The reverse lug pattern of the Trail-Specific Outsole and Rock Protection Plate provide excellent protection on a variety of uneven terrains. The new upper design has been updated for a more comfortable fit and durable performance, hugging the foot with modified MONO-SOCK® construction and Heel Clutching System™. Weight: 11.7 oz. Heel Height: 20mm. Forefoot Height: 10mm. Pronation is how a runners foot rolls medially between footfall and toeoff. Underpronation is when the foot rolls outwards, overpronation is when it rolls inwards, and a neutral pattern is when little rolling occurs. Matching a shoes properties with the runners running style will increase comfort, running efficiency, and contribute to decreasing the risk of injury.',
		fullprice: 270,
		discount: 0.15,
		stars: 3,
		size: ['12', '14', '16'],
		isfavorite: false,
		popularproduct: true
	}, {
		id: 7,
		name: 'Nike Free Black',
		imgthumb: 'nike_thumb',
		img1: 'nike1',
		img2: 'nike2',
		img3: 'nike3',
		category: 'Running shoe',
		brandlogo: 'assets/img/nike-logo.png',
		shortdescription: 'Nike Free RN er den klassiske Nike Free 5.0 i nye klæder. Opbygningen af skoen lader ingen tvivl om at vi har med en Nike Free at gøre.',
		longdescription: 'Nike Free RN er den klassiske Nike Free 5.0 i nye klæder. Opbygningen af skoen lader ingen tvivl om at vi har med en Nike Free at gøre. Overdelen er lavet i en Flymesh med zone inddelt ventilation, og Flywire i snøringen for at give et optimalt hold og støtte. Største nyhed er den nye mellemsålsopbygning. En auxetisk geometrisk opbygget mellemsål, giver efter og trækker sig sammen alt efter belastning. Det giver et mere naturligt bevægelsesmønster. Enginered mesh overdel med ventilationszoner. Flywire kabler for en tæt snøring og fast hold.',
		fullprice: 799.50,
		discount: 0.10,
		stars: 5,
		size: ['EU 36 Black', 'EU 38 Black', 'EU 39 Black'],
		isfavorite: false,
		popularproduct: true
	}, {
		id: 8,
		name: '3 GEL-FUJITRABUCO 5 G-TX',
		imgthumb: 'asics_thumb',
		img1: 'asics1',
		img2: 'asics2',
		img3: 'asics3',
		category: 'Running shoe',
		brandlogo: 'assets/img/brand_logo.jpg',
		shortdescription: 'God og robust terrænløbesko med GORE-TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod.',
		longdescription: 'The new GEL-FujiTrabuco™ 4 Neutral continues to offer off-road runners the balanced blend of cushioning, responsiveness, and versatile traction. The reverse lug pattern of the Trail-Specific Outsole and Rock Protection Plate provide excellent protection on a variety of uneven terrains. The new upper design has been updated for a more comfortable fit and durable performance, hugging the foot with modified MONO-SOCK® construction and Heel Clutching System™. Weight: 11.7 oz. Heel Height: 20mm. Forefoot Height: 10mm. Pronation is how a runners foot rolls medially between footfall and toeoff. Underpronation is when the foot rolls outwards, overpronation is when it rolls inwards, and a neutral pattern is when little rolling occurs. Matching a shoes properties with the runners running style will increase comfort, running efficiency, and contribute to decreasing the risk of injury.',
		fullprice: 549,
		discount: 0.15,
		stars: 3,
		size: ['12', '14', '16'],
		isfavorite: false,
		popularproduct: false
	}, {
		id: 9,
		name: '3 GEL-FUJITRABUCO 5 G-TX',
		imgthumb: 'asics_thumb',
		img1: 'asics1',
		img2: 'asics2',
		img3: 'asics3',
		category: 'Running shoe',
		brandlogo: 'assets/img/brand_logo.jpg',
		shortdescription: 'God og robust terrænløbesko med GORE-TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod.',
		longdescription: 'The new GEL-FujiTrabuco™ 4 Neutral continues to offer off-road runners the balanced blend of cushioning, responsiveness, and versatile traction. The reverse lug pattern of the Trail-Specific Outsole and Rock Protection Plate provide excellent protection on a variety of uneven terrains. The new upper design has been updated for a more comfortable fit and durable performance, hugging the foot with modified MONO-SOCK® construction and Heel Clutching System™. Weight: 11.7 oz. Heel Height: 20mm. Forefoot Height: 10mm. Pronation is how a runners foot rolls medially between footfall and toeoff. Underpronation is when the foot rolls outwards, overpronation is when it rolls inwards, and a neutral pattern is when little rolling occurs. Matching a shoes properties with the runners running style will increase comfort, running efficiency, and contribute to decreasing the risk of injury.',
		fullprice: 167,
		discount: 0.15,
		stars: 3,
		size: ['12', '14', '16'],
		isfavorite: false,
		popularproduct: false
	}, {
		id: 10,
		name: 'GEL-FUJITRABUCO 5 G-TX',
		imgthumb: 'asics_thumb',
		img1: 'asics1',
		img2: 'asics2',
		img3: 'asics3',
		category: 'Running shoe',
		brandlogo: 'assets/img/brand_logo.jpg',
		shortdescription: 'God og robust terrænløbesko med GORE-TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod.',
		longdescription: 'The new GEL-FujiTrabuco™ 4 Neutral continues to offer off-road runners the balanced blend of cushioning, responsiveness, and versatile traction. The reverse lug pattern of the Trail-Specific Outsole and Rock Protection Plate provide excellent protection on a variety of uneven terrains. The new upper design has been updated for a more comfortable fit and durable performance, hugging the foot with modified MONO-SOCK® construction and Heel Clutching System™. Weight: 11.7 oz. Heel Height: 20mm. Forefoot Height: 10mm. Pronation is how a runners foot rolls medially between footfall and toeoff. Underpronation is when the foot rolls outwards, overpronation is when it rolls inwards, and a neutral pattern is when little rolling occurs. Matching a shoes properties with the runners running style will increase comfort, running efficiency, and contribute to decreasing the risk of injury.',
		fullprice: 389,
		discount: 0.15,
		stars: 3,
		size: ['12', '14', '16'],
		isfavorite: false,
		popularproduct: false
	}, {
		id: 11,
		name: 'GEL-FUJITRABUCO 5 G-TX',
		imgthumb: 'asics_thumb',
		img1: 'asics1',
		img2: 'asics2',
		img3: 'asics3',
		category: 'Running shoe',
		brandlogo: 'assets/img/brand_logo.jpg',
		shortdescription: 'God og robust terrænløbesko med GORE-TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod.',
		longdescription: 'The new GEL-FujiTrabuco™ 4 Neutral continues to offer off-road runners the balanced blend of cushioning, responsiveness, and versatile traction. The reverse lug pattern of the Trail-Specific Outsole and Rock Protection Plate provide excellent protection on a variety of uneven terrains. The new upper design has been updated for a more comfortable fit and durable performance, hugging the foot with modified MONO-SOCK® construction and Heel Clutching System™. Weight: 11.7 oz. Heel Height: 20mm. Forefoot Height: 10mm. Pronation is how a runners foot rolls medially between footfall and toeoff. Underpronation is when the foot rolls outwards, overpronation is when it rolls inwards, and a neutral pattern is when little rolling occurs. Matching a shoes properties with the runners running style will increase comfort, running efficiency, and contribute to decreasing the risk of injury.',
		fullprice: 88.99,
		discount: 0.15,
		stars: 3,
		size: ['12', '14', '16'],
		isfavorite: false,
		popularproduct: true
	}, {
		id: 12,
		name: 'GEL-FUJITRABUCO 5 G-TX',
		imgthumb: 'asics_thumb',
		img1: 'asics1',
		img2: 'asics2',
		img3: 'asics3',
		category: 'Running shoe',
		brandlogo: 'assets/img/brand_logo.jpg',
		shortdescription: 'God og robust terrænløbesko med GORE-TEX-membran. Overdel i let mesh og sål med affjedring både i hæl og forfod.',
		longdescription: 'The new GEL-FujiTrabuco™ 4 Neutral continues to offer off-road runners the balanced blend of cushioning, responsiveness, and versatile traction. The reverse lug pattern of the Trail-Specific Outsole and Rock Protection Plate provide excellent protection on a variety of uneven terrains. The new upper design has been updated for a more comfortable fit and durable performance, hugging the foot with modified MONO-SOCK® construction and Heel Clutching System™. Weight: 11.7 oz. Heel Height: 20mm. Forefoot Height: 10mm. Pronation is how a runners foot rolls medially between footfall and toeoff. Underpronation is when the foot rolls outwards, overpronation is when it rolls inwards, and a neutral pattern is when little rolling occurs. Matching a shoes properties with the runners running style will increase comfort, running efficiency, and contribute to decreasing the risk of injury.',
		fullprice: 88.99,
		discount: 0.15,
		stars: 3,
		size: ['12', '14', '16'],
		isfavorite: false,
		popularproduct: true
	}];